# coding: utf-8

"""
    Cloudfoundry API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.authentication_type import AuthenticationType

class TestAuthenticationType(unittest.TestCase):
    """AuthenticationType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAuthenticationType(self):
        """Test AuthenticationType"""
        # inst = AuthenticationType()

if __name__ == '__main__':
    unittest.main()
