# coding: utf-8

"""
    Cloudfoundry API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.to_one_relationship import ToOneRelationship

class TestToOneRelationship(unittest.TestCase):
    """ToOneRelationship unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ToOneRelationship:
        """Test ToOneRelationship
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ToOneRelationship`
        """
        model = ToOneRelationship()
        if include_optional:
            return ToOneRelationship(
                data = {
                    'key' : ''
                    }
            )
        else:
            return ToOneRelationship(
                data = {
                    'key' : ''
                    },
        )
        """

    def testToOneRelationship(self):
        """Test ToOneRelationship"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
